server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: notificacion
              uri: lb://MS-NOTIFICACION
              predicates:
                - Path=/api/v1/notificaciones/**

            - id: cancelacion
              uri: lb://MS-CANCELACION
              predicates:
                - Path=/api/v1/cancelaciones/**

            - id: disponibilidad
              uri: lb://MS-DISPONIBILIDAD
              predicates:
                - Path=/api/v1/disponibilidades/**

            - id: historial-reserva
              uri: lb://MS-HISTORIAL-RESERVA
              predicates:
                - Path=/api/v1/historial-reservas/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}