spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://mysql-auth:3306/ms_autentificacion}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka-server:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false
    hostname: ms-autentificacion
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

jwt:
  secret: ${JWT_SECRET:ReservaProSecretKey2026SuperSecureForJWTGeneration}
  expiration: ${JWT_EXPIRATION:86400000}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  info:
    env:
      enabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

logging:
  level:
    root: INFO
    com.ReservaPro.ms_autentificacion: DEBUG
    com.netflix.discovery: DEBUG
  file:
    name: logs/ms-autentificacion.log

spring.cloud.compatibility-verifier.enabled: false