spring.application.name=ms-disponibilidad
server.port=8085

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/ms-disponibilidad}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=false

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

logging.level.root=INFO
logging.level.com.ReservaPro.ms_disponibilidad=INFO
logging.file.name=logs/microservicio-disponibilidad.log
